encoder_class:
  class_path: matsciml.models.FAENet
encoder_kwargs:
  act: silu
  cutoff: 6.0
  average_frame_embeddings: False
  pred_as_dict: False
  hidden_dim: 128
  out_dim: 128
  tag_hidden_channels: 0
output_kwargs:
  lazy: False
  input_dim: 128
  hidden_dim: 128
transforms:
  - class_path: matsciml.datasets.transforms.PeriodicPropertiesTransform
    init_args:
      cutoff_radius: 6.0
      adaptive_cutoff: True
  - class_path: matsciml.datasets.transforms.PointCloudToGraphTransform
    init_args:
      backend: pyg
      node_keys:
        - "pos"
        - "atomic_numbers"
  - class_path: matsciml.datasets.transforms.FrameAveraging
    init_args:
      frame_averaging: 3D
      fa_method: stochastic
