encoder_class:
  class_path: matsciml.models.FAENet
encoder_kwargs:
  act: silu
  cutoff: 6.0
  average_frame_embeddings: False
  pred_as_dict: False
  hidden_channels: 1024
  output_dim: 1
  tag_hidden_channels: 0
  pg_hidden_channels: 0
  num_filters: 512
  skip_co: "add"
  lr: 0.0001
output_kwargs:
  lazy: False
  input_dim: 1024
  hidden_dim: 1024
  num_hidden: 2
  dropout: 0.2
  activation:
    class_path: torch.nn.SiLU
transforms:
  - class_path: matsciml.datasets.transforms.PeriodicPropertiesTransform
    init_args:
      cutoff_radius: 6.0
      adaptive_cutoff: True
  - class_path: matsciml.datasets.transforms.PointCloudToGraphTransform
    init_args:
      backend: pyg
      node_keys:
        - "pos"
        - "atomic_numbers"
  - class_path: matsciml.datasets.transforms.pretraining.NoisyPositions
    init_args:
      scale: 0.1
      normalize: true
  - class_path: matsciml.datasets.transforms.FrameAveraging
    init_args:
      frame_averaging: 3D
      fa_method: stochastic
