encoder_class:
  class_path: matsciml.models.TensorNet
encoder_kwargs:
  element_types:
    class_path: matsciml.datasets.utils.element_types
  num_rbf: 32
  max_n: 3
  max_l: 3
output_kwargs:
  lazy: False
  input_dim: 64
  hidden_dim: 64
transforms:
  - class_path: matsciml.datasets.transforms.PeriodicPropertiesTransform
    init_args:
      cutoff_radius: 6.5
      adaptive_cutoff: True
  - class_path: matsciml.datasets.transforms.PointCloudToGraphTransform
    init_args:
      backend: dgl
      cutoff_dist: 20.0
      node_keys:
        - "pos"
        - "atomic_numbers"
